import os

CONF_THRESHOLD = float(os.getenv('CONF_THRESHOLD', '0.35'))
IOU_THRESHOLD = float(os.getenv('IOU_THRESHOLD', '0.50'))
SERVICE_VERSION = '0.1.0'
MODEL_VERSION = '8.4.0'
SCHEMA_VERSION = '1.0'
