import os

CONF_THRESHOLD = float(os.getenv("CONF_THRESHOLD", "0.45"))
IOU_THRESHOLD = float(os.getenv("IOU_THRESHOLD", "0.30"))
MODEL_BACKEND = os.getenv("MODEL_BACKEND", "pytorch").lower()
INFERENCE_IMAGE_SIZE = int(os.getenv("INFERENCE_IMAGE_SIZE", "640"))
MAX_UPLOAD_BYTES = int(os.getenv("MAX_UPLOAD_BYTES", str(10 * 1024 * 1024)))
LOW_CONFIDENCE_THRESHOLD = float(os.getenv("LOW_CONFIDENCE_THRESHOLD", "0.45"))
EDGE_MARGIN_PX = int(os.getenv("EDGE_MARGIN_PX", "5"))
EDGE_REVIEW_RATIO = float(os.getenv("EDGE_REVIEW_RATIO", "0.20"))
HIGH_DETECTION_COUNT = int(os.getenv("HIGH_DETECTION_COUNT", "12"))
FRAGMENT_MAX_GAP_RATIO = float(os.getenv("FRAGMENT_MAX_GAP_RATIO", "0.04"))
FRAGMENT_MIN_AXIS_OVERLAP = float(os.getenv("FRAGMENT_MIN_AXIS_OVERLAP", "0.60"))
FRAGMENT_MAX_AREA_RATIO = float(os.getenv("FRAGMENT_MAX_AREA_RATIO", "4.0"))
FRAGMENT_MAX_IOU = float(os.getenv("FRAGMENT_MAX_IOU", "0.02"))
FRAGMENT_MAX_DETECTIONS = int(os.getenv("FRAGMENT_MAX_DETECTIONS", "2"))
FRAGMENT_MIN_PAIRS = int(os.getenv("FRAGMENT_MIN_PAIRS", "1"))
SERVICE_VERSION = "0.2.0"
MODEL_NAME = "carton-yolov8n"
MODEL_VERSION = "ft-v1"
SCHEMA_VERSION = "1.1"
